{% set name = "cloudstor" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: {{ data.get('version') }}

source:
    path: ..

requirements:

  host:
    - python
    - pip
    - numpy
    - webdav
    - humanfriendly
    - pytest 
    - pytest-runner

  run:
    - pip
    - webdav
    - humanfriendly


# test:
#   requires:
#     - pytest 

#   source_files:
#       - tests/test_0_import.py

#   commands:
#     - pytest



about:
  home: "https://github.com/underworldcode/cloudstor"
  license: LGPL
  license_family: GPL
  license_file: LICENSE
  summary: "Python interface to the cloudstor (owncloud) storage facility provided by AARNET"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - lmoresi

